# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-10 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_remove_place_place_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='keywordSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=250)),
                ('grid_count', models.IntegerField()),
                ('grid_complete', models.IntegerField()),
            ],
        ),
    ]
