# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_keywordsummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='permanently_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='place',
            name='place_detail',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='place_id',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
