# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-16 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_tid', models.IntegerField()),
                ('p_name', models.TextField()),
                ('p_content', models.TextField()),
                ('p_comments', models.TextField()),
            ],
        ),
    ]
