# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-16 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantip', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_tid', models.IntegerField()),
                ('read', models.BooleanField(default=False)),
            ],
        ),
    ]
