# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-19 09:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantip', '0002_marktopic'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='p_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 19, 9, 3, 6, 254604)),
            preserve_default=False,
        ),
    ]
