# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-19 09:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pantip', '0003_topic_p_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='p_date',
            new_name='p_datetime',
        ),
    ]
